"""Does the arbitrariness in ΔC have a shape, or is it just slack?

`n3_anatomy` showed the transplant programme's ΔC is a convention, and
`n3_causal_delta_c` showed that removing the convention is harder than it
looks — a dictionary-free construction was *less* robust, for structural
reasons. Both leave the same question open, and it is the one that decides
whether the gap is interesting or merely annoying:

    the family of admissible ΔC readings is not a single number — but is it a
    single *axis*?

If every defensible convention moves the ΔC curve along essentially one
direction, then different observers are not disagreeing arbitrarily; they are
sitting at different points on one resolution scale, and the S-optimum's
dependence on the convention is a *lawful* dependence with one parameter. That
is a structure, and it can be named and quotiented out. If instead the
conventions move the curve in many independent directions, there is no such
axis and the reading is simply under-determined.

This module tests that directly, and the test is possible because of a
convenient fact: **on both substrates the ΔC convention changes only ΔC.** The
order parameter ΔI and the capacity load are read from the same trajectories
and do not depend on where the structured-overlap cut or the frequency bin
sits. So a family of conventions gives a family of ΔC curves over one fixed
scan, everything else held identical, and the question becomes the effective
rank of that family.

The method: stack the curves, normalise away the level (which is known to vary
and is not what is at stake — see :func:`shape_normalise`), and take the
singular values.

**The raw variance ratio is the wrong headline, and calibration says so.** A
family generated by *one* knob that slides a peak across the scan is
intrinsically one-dimensional, but it is a **curved** one-dimensional set, and
linear PCA charges several components to describe a curve. Measured on exactly
such a synthetic family — one Gaussian, peak position swept — PC1 explains only
**0.767** of the curve variance and ``rank_80`` reads **2**, while an
unstructured family of independent random curves gives **0.379** and rank 4. So
the ratio discriminates, but a threshold like "PC1 ≥ 0.8" would reject a family
that is one-dimensional by construction.

What survives calibration is the **functional** test, :func:`explained_by`.
Measured on synthetic families whose answers are known:

| family | PC1 | rank₈₀ | r²(PC1) on peak | gain from PC2 |
|---|---|---|---|---|
| one knob, sliding peak | 0.767 | 2 | **0.986** | +0.001 |
| independent random shapes | 0.379 | 4 | **0.240** | +0.517 |
| level changes only | degenerate | — | — | — |
| two knobs along one axis | 0.953 | 1 | **0.873** | +0.040 |
| two knobs, position × width | 0.740 | 2 | **0.934** | +0.004 |

The last row is the one to read carefully, and it fixes what may be claimed.
That family is genuinely **two**-dimensional in shape — but its *peak location*
depends only on the position knob, so a single score predicts it. The
functional test therefore answers **"is the consequence controlled by one
coordinate?"** and not "is the family one-dimensional?".  For the question here
that is the right target — a second convention direction that never reaches the
optimum is a difference without a consequence — but the distinction has to be
stated rather than blurred, and the claim below is only ever the former.
:func:`principal_axes` is reported as a diagnostic, never as the verdict.

:func:`axis_is_monotone` supplies the remaining requirement: a one-dimensional
family is only *interpretable* as a resolution scale if moving the convention
knob moves you monotonically along the axis. Low rank with a scrambled ordering
would be structure without meaning.
"""

from __future__ import annotations

import numpy as np

from .survival import spearman_r

__all__ = [
    "curve_matrix",
    "shape_normalise",
    "principal_axes",
    "axis_is_monotone",
    "explained_by",
]


def curve_matrix(curves) -> np.ndarray:
    """``(n_conventions, n_points)`` from a list of equal-length ΔC readings."""
    m = np.asarray([np.asarray(c, dtype=float) for c in curves], dtype=float)
    if m.ndim != 2:
        raise ValueError("all curves must have the same length")
    return m


def shape_normalise(m: np.ndarray) -> np.ndarray:
    """Centre and scale each curve to unit norm — compare shapes, not levels.

    The level is already known to move with the convention (a stricter cut
    counts fewer states, so ΔC falls everywhere), and that part is neither
    surprising nor interesting. What matters is whether the *profile across the
    scan* — where the reading rises, peaks and falls — moves along one direction
    or many. Rows that are entirely flat are left at zero rather than being
    amplified into noise by the division.
    """
    m = np.asarray(m, dtype=float)
    centred = m - m.mean(axis=1, keepdims=True)
    norms = np.linalg.norm(centred, axis=1, keepdims=True)
    return np.divide(centred, norms, out=np.zeros_like(centred),
                     where=norms > 1e-12)


def principal_axes(m: np.ndarray) -> dict:
    """Singular decomposition of the shape-normalised family.

    Returns the explained-variance ratios, the per-convention scores on each
    component, and the components themselves.  ``rank_80`` is the number of
    components needed to reach 80% — the headline number: 1 means one axis.
    """
    x = shape_normalise(m)
    x = x - x.mean(axis=0, keepdims=True)          # centre across conventions
    u, s, vt = np.linalg.svd(x, full_matrices=False)
    var = s ** 2
    total = float(var.sum())
    # every convention producing the SAME shape leaves numerical dust, not
    # structure; dividing by it manufactures ratios out of rounding error
    if total <= 1e-20 * max(1.0, float(np.abs(m).max()) ** 2):
        return {"explained": [], "cumulative": [], "scores": np.zeros_like(u),
                "components": vt, "rank_80": 0, "pc1": float("nan"),
                "degenerate": True}
    ratios = var / total
    cum = np.cumsum(ratios)
    return {"explained": ratios.tolist(),
            "cumulative": cum.tolist(),
            "scores": (u * s),                      # (n_conventions, n_comp)
            "components": vt,                       # (n_comp, n_points)
            "rank_80": int(np.searchsorted(cum, 0.80) + 1),
            "pc1": float(ratios[0]), "degenerate": False}


def axis_is_monotone(scores, parameter) -> dict:
    """Does the leading axis line up with the knob that generated the family?

    A one-dimensional family is only *interpretable* as a resolution scale if
    moving the convention parameter moves you monotonically along it. If the
    leading component is some mixture that jumps around as the cut is tightened,
    the family is low-rank by accident and the axis means nothing.
    """
    s = np.asarray(scores, dtype=float)
    p = np.asarray(parameter, dtype=float)
    rho = spearman_r(p, s)
    return {"spearman": float(rho), "monotone": bool(abs(rho) >= 0.9)}


def explained_by(scores, target, n_components: int = 2, *,
                 grid: float | None = None) -> dict:
    """How much of a downstream quantity the leading axes account for.

    ``target`` is whatever the convention was found to move — the ΔC peak
    location, the eviction capacity. Reports ``r2_pc1`` and the gain from adding
    the second component, because "one axis" only matters if that axis is what
    carries the consequence.

    ``grid`` is the spacing of the scan the target was read off. A target that
    moves by no more than one grid step across the whole family is **invariant**
    to the convention, and ``r²`` is then meaningless — there is no variance to
    explain, and the statistic will report a confident-looking failure driven by
    a single quantised outlier. That case is flagged rather than scored, because
    an invariant consequence is a *stronger* result than a one-dimensional one,
    and reading it as a failure inverts the finding.
    """
    s = np.asarray(scores, dtype=float)
    y = np.asarray(target, dtype=float)
    spread = float(y.max() - y.min()) if y.size else 0.0
    if y.size < 3 or np.allclose(y, y[0]):
        return {"r2_pc1": float("nan"), "r2_pc2": float("nan"),
                "gain": float("nan"), "degenerate": True,
                "invariant": True, "spread": spread, "n_distinct": 1}
    n_distinct = int(np.unique(np.round(y, 9)).size)
    if grid is not None and spread <= grid * 1.001:
        return {"r2_pc1": float("nan"), "r2_pc2": float("nan"),
                "gain": float("nan"), "degenerate": True,
                "invariant": True, "spread": spread,
                "n_distinct": n_distinct}

    def r2(k):
        a = np.column_stack([s[:, :k], np.ones(s.shape[0])])
        coef, *_ = np.linalg.lstsq(a, y, rcond=None)
        resid = y - a @ coef
        ss_res = float((resid ** 2).sum())
        ss_tot = float(((y - y.mean()) ** 2).sum())
        return 1.0 - ss_res / ss_tot if ss_tot > 0 else 0.0

    k = min(n_components, s.shape[1])
    r1 = r2(1)
    rk = r2(k) if k >= 2 else r1
    return {"r2_pc1": float(r1), "r2_pc2": float(rk),
            "gain": float(rk - r1), "degenerate": False,
            "invariant": False, "spread": spread, "n_distinct": n_distinct}
